const FirebaseConstants = {
	KEY: "AAAAFHNRulw:APA91bHcNjFacKGSdRCPND0sbskChRQK0vfqN7fb8ACoAfGB3IVJ_x66OgdksYVcfKvHLyv3i9m8bWzd6ydt9JTPscr_br1oEF6Z_lUVc-d9bh-2SF1G-yWHHbDGL8UhNTfyV1B9mDHm"
}

export default FirebaseConstants;